name: Karate API Tests

on:
  push:
    branches:
      - master  # adjust branch as needed
  pull_request:
    branches:
      - master  # adjust branch as needed
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Karate Standalone JAR
      run: |
        wget -O karate-standalone.jar https://github.com/intuit/karate/releases/download/v1.2.0/karate-1.2.0.jar

    - name: Run Karate Tests
      run: java -jar karate-standalone.jar src/test/java/karate